package com.example.lbctechnicaltest.viewmodels

import android.util.Log
import androidx.lifecycle.*
import com.example.lbctechnicaltest.models.utils.NetworkState
import io.reactivex.disposables.Disposable
import kotlinx.coroutines.*
import kotlin.coroutines.CoroutineContext

abstract class BaseViewModel : ViewModel(), CoroutineScope {
    companion object {
        const val TAG = "BaseViewModel"
    }

    override val coroutineContext: CoroutineContext
        get() = Dispatchers.IO

    /**
     * Displays a loader directly in the MainActivity
     */
    var loaderVisible = MutableLiveData<Boolean>()

    /**
     * Gives the fragment a state on the current request
     */
    var networkState = MutableLiveData<NetworkState>()

    /**
     * Disposes of the RX disposables generated by the children
     */
    protected val disposableList = mutableListOf<Disposable>()

    /**
     * Clears all the RX disposables
     */
    override fun onCleared() {
        Log.v(TAG, "onCleared")

        super.onCleared()

        disposableList.forEach { if (!it.isDisposed) it.dispose() }
    }
}